[workspace]
members = [
    "zkevm-circuits",
    "bus-mapping",
    "keccak256",
    "geth-utils",
]

[patch.crates-io]
halo2 = { git = "https://github.com/zcash/halo2.git", rev = "4283713ec76051eaf21a06d0279fa7d3497cafb6" }
