[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
bus-mapping = { path = "../bus-mapping"}
env_logger = "0.9.0"
ethers-providers = "0.6"
eth-types = { path = "../eth-types" }
halo2 = { git = "https://github.com/appliedzkp/halo2.git", rev = "b78c39cacc1c79d287032f1b5f94beb661b3fb42" }
log = "0.4.14"
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
rand = "0.8.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
zkevm-circuits = { path = "../zkevm-circuits", features = ["test"] }
