[package]
name = "circuit-benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.11"
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", tag = "v2022_03_06" }
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
ark-std = { version = "0.3", features = ["print-trace"] }
zkevm-circuits = { path = "../zkevm-circuits" }
keccak256 = { path = "../keccak256" }
bus-mapping = { path = "../bus-mapping" }
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10"
eth-types = { path = "../eth-types" }

[features]
default = []
benches = []
