[package]
name = "keccak256"
version = "0.1.0"
edition = "2018"

[features]
dev-graph = [ "plotters" ]

[dependencies]
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", branch = "kzg-rebase" }
itertools = "0.10.1"
num-bigint = "0.4.2"
num-traits = "0.2.14"
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
plotters = { version = "0.3.0", optional = true }

[dev-dependencies]
pretty_assertions = "1.0"
