[package]
name = "keccak256"
version = "0.1.0"
edition = "2018"

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]

[dependencies]
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", tag = "v2022_03_06" }
itertools = "0.10.1"
num-bigint = "0.4.2"
num-traits = "0.2.14"
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }
plotters = { version = "0.3.0", optional = true }
eth-types = { path = "../eth-types" } 
lazy_static = "1.4"

[dev-dependencies]
pretty_assertions = "1.0"
