[package]
name = "keccak256"
version = "0.1.0"
edition = "2018"

[features]
dev-graph = ["halo2/dev-graph", "plotters"]

[dependencies]
halo2 = "0.0"
itertools = "0.10.1"
num-bigint = "0.4.2"
num-traits = "0.2.14"
pasta_curves =  "0.1"
plotters = { version = "0.3.0", optional = true }
