[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
ethers = "0.6"
serde_json = "1.0.66"
serde = {version = "1.0.130", features = ["derive"] }
bus-mapping = { path = "../bus-mapping"}
eth-types = { path = "../eth-types"}
zkevm-circuits = { path = "../zkevm-circuits"}
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
url = "2.2.2"
pretty_assertions = "1.0.0"
log = "0.4.14"
env_logger = "0.9"
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", branch = "kzg-rebase" }
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256" }

[dev-dependencies]
pretty_assertions = "1.0.0"

[features]
default = []
rpc = []
circuit_input_builder = []
circuits = []
