name: GH Actions Prover Benches on PR
on:
  pull_request:
    types: [ labeled ,  ready_for_review]
jobs:
  Prover_benchmarking_Automation:
    if: contains(github.event.label.name, 'benchmarks')
    runs-on: pse-runner
    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: .github/proverCiScripts/wakeUpProver.sh
        shell: bash
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/rsSysstat.sh "${{ env.PR_NUMBER }}"
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/prepareProver.sh "${{ env.PR_NUMBER }}" "${{ github.workspace }}"
      - run: .github/proverCiScripts/deployToProver.sh "${{ env.PR_NUMBER }}" "${{ github.workspace }}"
        shell: bash
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/execBench.sh "${{ env.PR_NUMBER }}" 19 '"${{ github.event.label.name }}"'
        shell: bash
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/getSysstat.sh "${{ env.PR_NUMBER }}"
      - name: Calculate Benchmark Result
        if: success() || failure()
        run: .github/proverCiScripts/processResults.sh "${{ env.PR_NUMBER }}" '"${{ github.event.label.name }}"' "19"
        shell: bash
      - name: PowerOff prover
        if: always()
        run: .github/proverCiScripts/shutdownProver.sh
        shell: bash

