name: Prover Bench on halo2 PR
on:
  workflow_dispatch:
    inputs:
      event-type:
        required: true
        type: string
      ghuser:
        required: true
        type: string
      revision:
        required: true
        type: string
      halo2pr:
        required: true
        type: string
jobs:
  Exec-ProverBench-on-halo2-PR:
    runs-on: pse-runner
    env:
      GH_USER: ${{ github.event.inputs.ghuser }}
      HALO2PR: ${{ github.event.inputs.halo2pr }}
    steps:
      - run: echo "halo2 PR ${{ env.HALO2PR }} submitted by ${{ env.GH_USER }}"
      - run: echo "Running prover benchmarking due to ${{ github.event.inputs.event-type }}."        
      - uses: actions/checkout@v4
        with:
          ref: 'halo2benchmarking'
      - run: .github/proverCiScripts/wakeUpProver.sh
        shell: bash
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/rsSysstat.sh
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/prepareProver.sh "${{ github.event.inputs.halo2pr }}[halo2]" "${{ github.workspace }}"
      - run: .github/proverCiScripts/deployToProver.sh "${{ github.event.inputs.halo2pr }}[halo2]" "${{ github.workspace }}"
        shell: bash
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/injectHalo2Revision.sh "${{ github.event.inputs.halo2pr }}[halo2]" "${{ github.event.inputs.revision }}"
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/execBench.sh "${{ github.event.inputs.halo2pr }}[halo2]" 19
        shell: bash
      - run: |
          ssh prover "bash -s" -- < .github/proverCiScripts/getSysstat.sh "${{ github.event.inputs.halo2pr }}[halo2]"
      - run: .github/proverCiScripts/shutdownProver.sh
        shell: bash
